openToken: openMissionJmH0DQuVfTGw2D8iw9xtCLiW9SllZQAFAUE5Xuypgy50G?L2HgIDe

# ВЕСЬ ТЕКСТ ЗДЕСЬ ПОДДЕРЖИВАЕТ MINIMESSAGE (Загуглите)

missionCategories:
  main:
    - Главные задания
  side:
    - Побочные

# Список миссий
missions:
  stick:
    titles:
      - Принести палку
      - <color:#93ff59><b><u>Из красного леса</u></b></color>
    description:
      - ZOV <b>brbrbrb</b>
      - brbrbr no br
    category: "main"

# Количество строк в книге (лучше это не трогать, но пусть будет)
maxLines: 14

# Формат разделения заданий в меню заданий
# "" - никакого разделения | " " - пустая строка | "<текст>" - разделителем будет какой-то текст, например можно указать "---"
splitFormat: ""