name: StoryKeeper
version: '1.1'
main: AronHuisInCo.storyKeeper.StoryKeeper
api-version: '1.21'

commands:
  storyReload:
    description: "Перезагрузка"
    usage: "/storyReload"
    permission: AronHuisInCo.story
  openMission:
    description: "Открывает описание миссии"
    usage: "/openMission :)"
  openMissions:
    description: "Открывает миссии"
    usage: "/openMissions"
  msnget:
    description: "Получить состояние миссии у игрока"
    usage: "/msnget <player>"
    permission: AronHuisInCo.story
  msnset:
    description: "Изменить состояние миссии у игрока"
    usage: "/msnset <player> <true|false>"
    permission: AronHuisInCo.story

permissions:
  AronHuisInCo.story:
    default: op

softdepend: ["PlaceholderAPI"]
